# Generated by Django 3.2.6 on 2022-09-20 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0052_auto_20200801_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='type',
        ),
        migrations.AddField(
            model_name='machine',
            name='desp',
            field=models.CharField(default='hii', max_length=150),
        ),
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('green', 'WORKING'), ('yellow', 'UNDER REPAIR'), ('red', 'NOT WORKING')], default='green', max_length=10),
        ),
    ]
