# Generated by Django 3.2.6 on 2022-09-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0053_auto_20220920_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Fblink',
        ),
    ]
